name: Generate packages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deb-packages:
    uses: ./.github/workflows/deb-packages.yml

  rpm-packages:
    uses: ./.github/workflows/rpm-packages.yml

  arch-packages:
    uses: ./.github/workflows/arch-packages.yml

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [rpm-packages, deb-packages, arch-packages]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List artifacts
        run: ls -R dist

      - name: Create Release
        if: ${{ !github.event.act }} # skip during local actions testing
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.deb
            dist/**/*.rpm
            dist/**/*.pkg.tar.zst
            dist/**/*.tar.gz
            dist/**/PKGBUILD
